// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Datasource representing an OIDC application belonging to a project, with all configuration possibilities.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-zitadel/sdk/go/zitadel"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			oidcApplicationApplicatoinOidc, err := zitadel.GetApplicatoinOidc(ctx, &zitadel.GetApplicatoinOidcArgs{
//				OrgId:     data.Zitadel_org.Org.Id,
//				ProjectId: data.Zitadel_project.Project.Id,
//				AppId:     "177073626925760515",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("oidcApplication", oidcApplicationApplicatoinOidc)
//			return nil
//		})
//	}
//
// ```
func GetApplicatoinOidc(ctx *pulumi.Context, args *GetApplicatoinOidcArgs, opts ...pulumi.InvokeOption) (*GetApplicatoinOidcResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetApplicatoinOidcResult
	err := ctx.Invoke("zitadel:index/getApplicatoinOidc:getApplicatoinOidc", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApplicatoinOidc.
type GetApplicatoinOidcArgs struct {
	// The ID of this resource.
	AppId string `pulumi:"appId"`
	// orgID of the application
	OrgId string `pulumi:"orgId"`
	// ID of the project
	ProjectId string `pulumi:"projectId"`
}

// A collection of values returned by getApplicatoinOidc.
type GetApplicatoinOidcResult struct {
	// Access token role assertion
	AccessTokenRoleAssertion bool `pulumi:"accessTokenRoleAssertion"`
	// Access token type
	AccessTokenType string `pulumi:"accessTokenType"`
	// Additional origins
	AdditionalOrigins []string `pulumi:"additionalOrigins"`
	// The ID of this resource.
	AppId string `pulumi:"appId"`
	// App type
	AppType string `pulumi:"appType"`
	// Auth method type
	AuthMethodType string `pulumi:"authMethodType"`
	// Clockskew
	ClockSkew string `pulumi:"clockSkew"`
	// Dev mode
	DevMode bool `pulumi:"devMode"`
	// Grant types
	GrantTypes []string `pulumi:"grantTypes"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// ID token role assertion
	IdTokenRoleAssertion bool `pulumi:"idTokenRoleAssertion"`
	// Token userinfo assertion
	IdTokenUserinfoAssertion bool `pulumi:"idTokenUserinfoAssertion"`
	// Name of the application
	Name string `pulumi:"name"`
	// orgID of the application
	OrgId string `pulumi:"orgId"`
	// Post logout redirect URIs
	PostLogoutRedirectUris []string `pulumi:"postLogoutRedirectUris"`
	// ID of the project
	ProjectId string `pulumi:"projectId"`
	// RedirectURIs
	RedirectUris []string `pulumi:"redirectUris"`
	// Response type
	ResponseTypes []string `pulumi:"responseTypes"`
	// Version
	Version string `pulumi:"version"`
}

func GetApplicatoinOidcOutput(ctx *pulumi.Context, args GetApplicatoinOidcOutputArgs, opts ...pulumi.InvokeOption) GetApplicatoinOidcResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetApplicatoinOidcResult, error) {
			args := v.(GetApplicatoinOidcArgs)
			r, err := GetApplicatoinOidc(ctx, &args, opts...)
			var s GetApplicatoinOidcResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetApplicatoinOidcResultOutput)
}

// A collection of arguments for invoking getApplicatoinOidc.
type GetApplicatoinOidcOutputArgs struct {
	// The ID of this resource.
	AppId pulumi.StringInput `pulumi:"appId"`
	// orgID of the application
	OrgId pulumi.StringInput `pulumi:"orgId"`
	// ID of the project
	ProjectId pulumi.StringInput `pulumi:"projectId"`
}

func (GetApplicatoinOidcOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetApplicatoinOidcArgs)(nil)).Elem()
}

// A collection of values returned by getApplicatoinOidc.
type GetApplicatoinOidcResultOutput struct{ *pulumi.OutputState }

func (GetApplicatoinOidcResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetApplicatoinOidcResult)(nil)).Elem()
}

func (o GetApplicatoinOidcResultOutput) ToGetApplicatoinOidcResultOutput() GetApplicatoinOidcResultOutput {
	return o
}

func (o GetApplicatoinOidcResultOutput) ToGetApplicatoinOidcResultOutputWithContext(ctx context.Context) GetApplicatoinOidcResultOutput {
	return o
}

// Access token role assertion
func (o GetApplicatoinOidcResultOutput) AccessTokenRoleAssertion() pulumi.BoolOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) bool { return v.AccessTokenRoleAssertion }).(pulumi.BoolOutput)
}

// Access token type
func (o GetApplicatoinOidcResultOutput) AccessTokenType() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) string { return v.AccessTokenType }).(pulumi.StringOutput)
}

// Additional origins
func (o GetApplicatoinOidcResultOutput) AdditionalOrigins() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) []string { return v.AdditionalOrigins }).(pulumi.StringArrayOutput)
}

// The ID of this resource.
func (o GetApplicatoinOidcResultOutput) AppId() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) string { return v.AppId }).(pulumi.StringOutput)
}

// App type
func (o GetApplicatoinOidcResultOutput) AppType() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) string { return v.AppType }).(pulumi.StringOutput)
}

// Auth method type
func (o GetApplicatoinOidcResultOutput) AuthMethodType() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) string { return v.AuthMethodType }).(pulumi.StringOutput)
}

// Clockskew
func (o GetApplicatoinOidcResultOutput) ClockSkew() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) string { return v.ClockSkew }).(pulumi.StringOutput)
}

// Dev mode
func (o GetApplicatoinOidcResultOutput) DevMode() pulumi.BoolOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) bool { return v.DevMode }).(pulumi.BoolOutput)
}

// Grant types
func (o GetApplicatoinOidcResultOutput) GrantTypes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) []string { return v.GrantTypes }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetApplicatoinOidcResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) string { return v.Id }).(pulumi.StringOutput)
}

// ID token role assertion
func (o GetApplicatoinOidcResultOutput) IdTokenRoleAssertion() pulumi.BoolOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) bool { return v.IdTokenRoleAssertion }).(pulumi.BoolOutput)
}

// Token userinfo assertion
func (o GetApplicatoinOidcResultOutput) IdTokenUserinfoAssertion() pulumi.BoolOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) bool { return v.IdTokenUserinfoAssertion }).(pulumi.BoolOutput)
}

// Name of the application
func (o GetApplicatoinOidcResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) string { return v.Name }).(pulumi.StringOutput)
}

// orgID of the application
func (o GetApplicatoinOidcResultOutput) OrgId() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) string { return v.OrgId }).(pulumi.StringOutput)
}

// Post logout redirect URIs
func (o GetApplicatoinOidcResultOutput) PostLogoutRedirectUris() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) []string { return v.PostLogoutRedirectUris }).(pulumi.StringArrayOutput)
}

// ID of the project
func (o GetApplicatoinOidcResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

// RedirectURIs
func (o GetApplicatoinOidcResultOutput) RedirectUris() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) []string { return v.RedirectUris }).(pulumi.StringArrayOutput)
}

// Response type
func (o GetApplicatoinOidcResultOutput) ResponseTypes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) []string { return v.ResponseTypes }).(pulumi.StringArrayOutput)
}

// Version
func (o GetApplicatoinOidcResultOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicatoinOidcResult) string { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetApplicatoinOidcResultOutput{})
}
